application: mukiolib
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /(.*\.(html|css|js|txt|gif|png|jpg|ico|swf|cur|xml))
  static_files: static/\1
  upload: static/(.*\.(html|css|js|txt|gif|png|jpg|ico|swf|cur|xml))
- url: /crossdomain\.xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain\.xml
- url: /.*
  script: main.py
